Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "opscode-ubuntu-14.04"
  c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box"
  c.vm.hostname = "default-ubuntu-1404"
  c.vm.network(:forwarded_port, {:guest=>1337, :host=>1337})
  c.vm.network(:forwarded_port, {:guest=>27017, :host=>27017})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", "1024"]
    p.customize ["modifyvm", :id, "--cpus", "2"]
  end
end
